const mongoose = require("mongoose");

const bondDetailSchema = new mongoose.Schema(
  {
    basDt: String,
    crno: String,
    scrsItmsKcd: String,
    isinCd: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    scrsItmsKcdNm: String,
    bondIsurNm: String,
    isinCdNm: String,
    bondIssuDt: String,
    bondIssuAmt: String,
    bondIssuCurCd: String,
    optnTcd: String,
    optnTcdNm: String,
    bondIssuCurCdNm: String,
    sicNm: String,
    bondExprDt: String,
    intCmpuMcd: String,
    intCmpuMcdNm: String,
    bondPymtAmt: String,
    irtChngDcd: String,
    irtChngDcdNm: String,
    bondSrfcInrt: String,
    bondBal: String,
    grnDcd: String,
    bondIntTcd: String,
    bondIntTcdNm: String,
    grnDcdNm: String,
    bondRnknDcd: String,
    bondRnknDcdNm: String,
    pclrBondKcd: String,
    pclrBondKcdNm: String,
    lstgDt: String,
    bondOffrMcd: String,
    bondOffrMcdNm: String,
    txtnDcd: String,
    txtnDcdNm: String,
    pamtRdptMcd: String,
    pamtRdptMcdNm: String,
    stripsPsblYn: String,
    stripsNm: String,
    prisLnkgBondYn: String,
    piamPayInstNm: String,
    piamPayBrofNm: String,
    cptUsgeDcd: String,
    cptUsgeDcdNm: String,
    bondRegInstDcd: String,
    bondRegInstDcdNm: String,
    issuDptyNm: String,
    bondUndtInstNm: String,
    bondGrnInstNm: String,
    cpbdMngCmpyNm: String,
    crfndYn: String,
    prmncBondYn: String,
    qibTrgtScrtYn: String,
    prmncBondTmnDt: String,
    rgtExertMnbdDcd: String,
    rgtExertMnbdDcdNm: String,
    qibTmnDt: String,
    intPayCyclCtt: String,
    nxtmCopnDt: String,
    rbfCopnDt: String,
    bnkHldyIntPydyDcd: String,
    bnkHldyIntPydyDcdNm: String,
    sttrHldyIntPydyDcd: String,
    sttrHldyIntPydyDcdNm: String,
    intPayMmntDcd: String,
    intPayMmntDcdNm: String,
    elpsIntPayYn: String,
    kisScrsItmsKcd: String,
    kisScrsItmsKcdNm: String,
    kbpScrsItmsKcd: String,
    kbpScrsItmsKcdNm: String,
    niceScrsItmsKcd: String,
    niceScrsItmsKcdNm: String,
    fnScrsItmsKcd: String,
    fnScrsItmsKcdNm: String,
  },
  {
    timestamps: true,
    collection: "bond_details",
  }
);

// 모델 생성
const BondDetail = mongoose.model("BondDetail", bondDetailSchema);

module.exports = BondDetail;
